### ISSUE TITLE
Could not retrieve a valid handle. Exiting.

### ISSUE THREAD

**Issue by badboycxcc** [Kudaes/Dumpy#4]

**Comment by badboycxcc** [comment]
![飞书20230404-144641](https://user-images.githubusercontent.com/72059221/229710392-2af26c8f-8ca5-4eff-96d1-e7421cc5550e.jpg)

**Comment by Kudaes** [comment]
It is not guaranteed the presence of an open handle to the lsass when you run Dumpy on a system, that's why I implemented the abuse of the race condition in the seclogon service.
Try running the tool once again but using the --force flag as well, this should solve your issue.

**Comment by badboycxcc** [comment]
![飞书20230406-091134](https://user-images.githubusercontent.com/72059221/230247835-d37011db-a894-4609-a970-a4be20a29b4d.jpg)


It can be grabbed, but Mimikatz failed to get it.

**Comment by badboycxcc** [comment]
![飞书20230406-091036](https://user-images.githubusercontent.com/72059221/230247731-0f185022-95fa-423e-8616-5bddeae35736.jpg)
![飞书20230406-091032](https://user-images.githubusercontent.com/72059221/230247742-67f42987-2263-4bc8-b342-054629e3b586.jpg)

**Comment by badboycxcc** [comment]
Is it my decryption method wrong?

**Comment by Kudaes** [comment]
The decryption process seems fine.
Try to open the decrypted dump file either on a text editor or on a hex editor. The ASCII representation of the first few bytes should be the string MDMP. If so, then the decryption went right.
In that case, I would think of two possibilities:
* Are you running Mimikatz on Windows 11? I've seen some issues related to that OS version, I would recommend to parse the dump file on a Win10 machine.
* is there any EDR in place that could be messing up with the dumping process?

**Comment by badboycxcc** [comment]
Oh, it can be Dump but not encrypted on Windows 11, but it works well on Windows 10.
Windows 11
![11](https://user-images.githubusercontent.com/72059221/231027245-10c8b831-a922-4970-9c3f-81b79720b9af.jpg)
![12](https://user-images.githubusercontent.com/72059221/231027261-4015720d-0ab4-4238-b2ad-8e569382b07d.jpg)

Windows 10
![10](https://user-images.githubusercontent.com/72059221/231027273-8bd2571f-baf5-4ba4-ac10-e3fb1c66ac84.jpg)

**Comment by Kudaes** [comment]
I see, I think it is a Mimikatz issue, but I cant not ensure it. I'll try to test it myself on a Win11.

What happens if you obtain the dump from a Win11 and perform the parse with Mimikatz on the Windows 10 host?¿

**Comment by badboycxcc** [comment]
Oh, I have tested it. There is Win 10 in the Win 11 dump and it cannot be decrypted.

**Comment by Kudaes** [comment]
I've finally tested the tool on both Win10 and Win11 and it works as intended.
