### ISSUE TITLE
I got an error when using cargo to compile.

### ISSUE THREAD

**Issue by Ptkatz** [Kudaes/Dumpy#5]
set LITCRYPT_ENCRYPT_KEY="yoursupersecretkey"

cargo build --target=x86_64-pc-windows-msvc

...
error: assigning to `&T` is undefined behavior, consider using an `UnsafeCell`
   --> dinvoke\src\lib.rs:242:21
    |
234 |                 let mut fun_name: *mut String = std::mem::transmute(&String::default());
    |                                                 --------------------------------------- casting happend here
...
242 |                     *fun_name = function_name.to_string();
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, visit <https://doc.rust-lang.org/book/ch15-05-interior-mutability.html>
    = note: `#[deny(invalid_reference_casting)]` on by default

error: could not compile `dinvoke` (lib) due to 1 previous error

**Comment by Kudaes** [comment]
Hi, those error appeared since Rust 1.73.0 version on many of my projects. I just pushed a commit on Dumpy that should fix it, so please give it a try and let me know how it went.
